services:
  calculator_app:
    build: calculator_app/
    ports:
      - "5000:5000"
    networks:
      - calculator_network
    depends_on:
      - calculator_db
  calculator_db:
    image: postgres:13
    environment:
      POSTGRES_USER: calculator
      POSTGRES_PASSWORD: calculator
      POSTGRES_DB: calculator
    networks:
      - calculator_network
    volumes:
      - calculator_db_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
networks:
  calculator_network:
    driver: bridge
volumes:
  calculator_db_data: